<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJpCBZ4P\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJpCBZ4P/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJpCBZ4P.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJpCBZ4P\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJpCBZ4P\App_KernelDevDebugContainer([
    'container.build_hash' => 'JpCBZ4P',
    'container.build_id' => '8ef3d168',
    'container.build_time' => 1580840737,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJpCBZ4P');
